name: Publish

on:
  repository_dispatch:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build Site
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm run build
      env:
        GHOST_API_URL: ${{ secrets.GHOST_API_URL}}
        GHOST_CONTENT_API_KEY: ${{ secrets.GHOST_CONTENT_API_KEY }}
        SITE_URL: ${{ secrets.SITE_URL}}
    - name: Deploy to server
      uses: Pendect/action-rsyncer@v1.1.0
      env:
        DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
        DEPLOY_USER: ${{ secrets.USER }}
        DEPLOY_HOST: ${{ secrets.HOST }}
        DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
      with:
        flags: '-vazuk'
        src: 'dist/'
        dest: "$DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH"